package;

/*
	DO NOT EDIT THIS FILE DIRECTLY
	This file was generated by a script in FMOD Studio 
 */
// @formatter:off
enum FmodSong {
    LetsGo;
}

enum FmodSFX {
    MenuHover;
    MenuSelect;
}

class FmodEvent {
    public static inline extern overload function event(song:FmodSong):String {
        return switch(song) {
            case LetsGo: "event:/Music/LetsGo";
        }
    }
    public static inline extern overload function event(sfx:FmodSFX):String {
        return switch(sfx) {
            case MenuHover: "event:/SFX/Menu/MenuHover";
            case MenuSelect: "event:/SFX/Menu/MenuSelect";
        }
    }
}
