package;

/*
	DO NOT EDIT THIS FILE DIRECTLY
	This file was generated by a script in FMOD Studio 
 */
// @formatter:off
enum FmodSongE {
    LetsGo;
}

enum FmodSFXE {
    MenuHover;
    MenuSelect;
}

enum FmodBusE {
    Master;
    Music;
    SFX;
}

class FmodPath {
    public static inline extern overload function path(song:FmodSongE):String {
        return switch(song) {
            case LetsGo: "event:/Music/LetsGo";
        }
    }
    public static inline extern overload function path(sfx:FmodSFXE):String {
        return switch(sfx) {
            case MenuHover: "event:/SFX/Menu/MenuHover";
            case MenuSelect: "event:/SFX/Menu/MenuSelect";
        }
    }
    public static inline extern overload function path(bus:FmodBusE):String {
        return switch(bus) {
            case Master: "bus:/";
            case Music: "bus:/Music";
            case SFX: "bus:/SFX";
        }
    }
}
