/*
	DO NOT EDIT THIS FILE DIRECTLY
	This file was generated by a script in FMOD Studio 
 */

package;

enum FmodSong {
	LetsGo;
}

enum FmodSFX {
	Boink;
	MenuHover;
	MenuSelect;
}

class FmodEvent {
	public static function music(song:FmodSong):String {
		return switch (song) {
			case LetsGo: "event:/Music/LetsGo";
		}
	}

	public static function sfx(sfx:FmodSFX):String {
		return switch (sfx) {
			case Boink: "event:/SFX/Menu/Boink";
			case MenuHover: "event:/SFX/Menu/MenuHover";
			case MenuSelect: "event:/SFX/Menu/MenuSelect";
		}
	}
}
