package;

/*
	DO NOT EDIT THIS FILE DIRECTLY
	This file was generated by a script in FMOD Studio 
 */
// @formatter:off
class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
}
class FmodBus {
    public static inline var Master:String = "bus:/";
    public static inline var Music:String = "bus:/Music";
    public static inline var SFX:String = "bus:/SFX";
}
